"""AgentSpec — the one artifact every creation method converges into."""

import re
from pathlib import PurePosixPath
from typing import Any, Literal

from pydantic import BaseModel, Field, field_validator, model_validator

from app.schemas.attachments import AttachmentRequest, SessionIdField
from app.schemas.inbound_auth import JWT_CAPABLE_METHODS, InboundAuth
from app.schemas.requirements import assert_all_pinned

# Latest Sonnet inference profile available in the target account (verified via
# bedrock list-inference-profiles; there is no "sonnet-5" profile).
DEFAULT_MODEL_ID = "global.anthropic.claude-sonnet-5"

Method = Literal["harness", "zip_runtime", "container", "studio", "byoc"]

# Which agent SDK the "container" method packages. The console presents that
# method as the "Other Agent SDK" entrance with this as a second-level choice,
# so the category can gain members without migrating stored specs. There is
# deliberately NO dispatch on this field yet: with one member, a dispatch table
# would be an abstraction over nothing — app/deployer/container.py and
# app/templates/claude_sdk_agent/ stay unconditional until a second SDK exists.
AgentSdk = Literal["claude_agent_sdk"]

# Which model-hosting surface the model_id belongs to. It selects the harness
# bedrockModelConfig.apiFormat (mantle → responses, bedrock → converse_stream);
# both stay on the bedrockModelConfig union branch, so no API key is involved.
ModelSource = Literal["bedrock", "mantle"]

# Per-model-call reasoning effort for OpenAI GPT-5.x / GPT-6 models (same effort
# scale). Consumed by the harness method only and only for an OpenAI model reached
# through native Bedrock (``model_source="bedrock"``), where the platform knows the exact Converse
# pass-through shape (``additionalModelRequestFields.reasoning.effort``). Absent ⇒
# nothing is sent and the model's own default applies.
ReasoningEffort = Literal["low", "medium", "high"]

# Ceiling for ``AgentSpec.max_tokens`` (per model call). The service model bounds
# ``bedrockModelConfig.maxTokens`` from below only; a too-large value surfaces as a
# model-side validation error, so this cap is a sanity bound, not a model catalogue.
MAX_TOKENS_CEILING = 131072
# Per-call ceiling a Harness on an OpenAI GPT model gets when the spec sets none: the
# service default is too small for their hidden reasoning (live 2026-10-04: a GPT-6
# call reasoned for 95 s and stopped at max_tokens before writing any answer). Other
# families keep the service default — Bedrock rejects a value above a model's limit.
DEFAULT_GPT_MAX_TOKENS = 65536


def display_name_of(spec: dict[str, Any] | None) -> str | None:
    """The stored spec's ``display_name`` (None when unset) — list/detail projection.

    Read defensively: specs written before the field existed simply lack it.
    """
    value = (spec or {}).get("display_name")
    return (value.strip() or None) if isinstance(value, str) else None


def is_openai_model_id(model_id: str) -> bool:
    """``openai.<model>`` bare id or any inference-profile-prefixed form of it."""
    return "openai." in model_id


# Methods that can mount managed knowledge bases. studio is excluded: its code is
# generated by the vendored canvas, which has no place to inject a retrieval tool.
KB_METHODS = {"harness", "zip_runtime", "container"}

# A named, platform-owned bundle of local @tool functions compiled into the
# generated runtime. Deliberately NOT a ToolRef.type member: every existing member
# denotes an *external* resource that drives IAM and deployer behaviour, while a
# toolkit drives neither — it only changes which functions the template emits.
# Adding it to ToolRef would put a member inside _uses_gateway()'s blast radius
# (app/services/agent_iam.py) that needs no workload token.
# See app/templates/toolkits/ and .trellis/spec/launchpad/agent-toolkits.md.
Toolkit = Literal["hr_assistant"]


_REST_TOOL_NAME_RE = re.compile(r"^[a-zA-Z][a-zA-Z0-9_-]{0,63}$")
CONNECTION_NAME_RE = r"^[a-zA-Z0-9\-_]{1,128}$"
# Tool-level auth is honoured by exactly these methods: zip_runtime renders the
# generated identity client, byoc gets the declaration (IAM + env) for its own code.
TOOL_AUTH_METHODS = ("zip_runtime", "byoc")
# Acting modes implemented today; the schema accepts the others so a stored spec
# stays loadable, and request-time validation refuses them (identity_providers).
SUPPORTED_ACTING_MODES = ("as_agent", "as_user")


class ApiKeyPlacement(BaseModel):
    """Where the runtime puts a fetched API key.

    The default renders ``Authorization: Bearer <key>``; any other header name
    sends the bare key (``x-api-key: <key>``), as does a query parameter.
    """

    in_: Literal["header", "query"] = Field(default="header", alias="in")
    name: str = Field(default="Authorization", min_length=1, max_length=128)

    # stored and echoed as {"in": ...} — the console's field name
    model_config = {"populate_by_name": True, "serialize_by_alias": True}


# legacy (earlier fork) flow → (kind, mode)
_LEGACY_FLOWS = {
    "M2M": ("oauth2", "as_agent"),
    "API_KEY": ("api_key", "as_agent"),
    "USER_FEDERATION": ("oauth2", "as_user"),
}


class ToolAuth(BaseModel):
    """Outbound auth for one tool, backed by a Connection (an AgentCore Identity
    credential provider in this workspace's token vault).

    ``connection`` names the credential provider (not its ARN). Whether it exists
    — and whether its kind matches ``kind`` — is validated at request time against
    the live vault (``services.identity_providers.validate_tool_auth``), not here:
    the valid name space lives in AWS, and a stored spec must keep validating
    after its Connection is deleted (the next save fails loudly instead).

    Declared on the schema on purpose: ``AgentSpec`` ignores unknown keys, so an
    undeclared ``auth`` would be dropped silently on every save.
    """

    connection: str = Field(pattern=CONNECTION_NAME_RE)
    kind: Literal["oauth2", "api_key"]
    mode: Literal["as_agent", "as_user", "obo"] = "as_agent"
    scopes: list[str] = Field(default_factory=list, max_length=32)
    audience: str | None = Field(default=None, max_length=512)
    # api_key only: key placement. None ⇒ Authorization: Bearer <key>.
    api_key: ApiKeyPlacement | None = None

    @model_validator(mode="before")
    @classmethod
    def _legacy_shape(cls, data: Any) -> Any:
        """Accept the earlier fork's ``{provider, flow}`` vocabulary."""
        if not isinstance(data, dict):
            return data
        data = dict(data)
        if "connection" not in data and "provider" in data:
            data["connection"] = data.pop("provider")
        flow = data.pop("flow", None)
        if flow in _LEGACY_FLOWS:
            kind, mode = _LEGACY_FLOWS[flow]
            data.setdefault("kind", kind)
            data.setdefault("mode", mode)
        data.pop("force_reauth", None)
        return data

    @model_validator(mode="after")
    def _kind_shape(self) -> "ToolAuth":
        if self.kind == "api_key":
            if self.scopes:
                raise ValueError("scopes apply to oauth2 Connections only")
            if self.audience:
                raise ValueError("audience applies to oauth2 Connections only")
            if self.mode != "as_agent":
                raise ValueError("an api_key Connection can only act as the agent")
        elif self.api_key is not None:
            raise ValueError("api_key placement applies to api_key Connections only")
        for scope in self.scopes:
            if not scope or len(scope) > 256:
                raise ValueError("each scope must be 1-256 characters")
        return self


class ToolRef(BaseModel):
    """Reference to a tool the agent may call.

    type=builtin → AgentCore builtin (code-interpreter / browser)
    type=gateway → MCP tool via the shared gateway (wired in phase 6)
    type=mcp     → remote MCP server URL
    type=rest    → plain HTTP API (config.url) called directly from the runtime;
                   carries ``auth`` when the API is protected
    """

    type: Literal["builtin", "gateway", "mcp", "rest"]
    name: str
    config: dict[str, Any] = Field(default_factory=dict)
    # Tool-level outbound auth (rest/mcp only). type=gateway stays implicit: the
    # gateway authenticates its own targets (see routers/identity gateway targets).
    # Omitted from the dump when unset, so a stored spec without tool auth keeps
    # its exact pre-identity shape.
    auth: ToolAuth | None = Field(default=None, exclude_if=lambda v: v is None)

    @model_validator(mode="after")
    def _gateway_tool_list(self) -> "ToolRef":
        # type=gateway may carry ``config.tools``: the exact MCP tool names this
        # attachment may call (the record's declared tools, optionally narrowed).
        # Absent = legacy spec → the record's own ``<name>___*`` target scope.
        if self.type != "gateway" or "tools" not in self.config:
            return self
        tools = self.config["tools"]
        if (
            not isinstance(tools, list)
            or not 1 <= len(tools) <= MAX_GATEWAY_TOOLS
            or not all(isinstance(t, str) and _GATEWAY_TOOL_RE.match(t) for t in tools)
            or len(set(tools)) != len(tools)
        ):
            raise ValueError(
                f"gateway tool {self.name!r}: config.tools must be 1–{MAX_GATEWAY_TOOLS} "
                "distinct MCP tool names ([A-Za-z0-9_.-], ≤ 128 characters)"
            )
        return self


class KnowledgeBaseRef(BaseModel):
    """Managed Knowledge Base mounted on the agent via the shared KB gateway.

    name/description are denormalized at selection time — they feed the system
    prompt and detail views without a Bedrock round-trip.
    """

    kb_id: str = Field(min_length=1, max_length=32, pattern=r"^[A-Za-z0-9]+$")
    name: str = Field(default="", max_length=200)
    description: str = Field(default="", max_length=1000)


class GuardrailConfig(BaseModel):
    """PII protection applied by the platform on both ends of a turn (T12).

    Off by default and independent of the creation method: the screen runs in the
    platform's invoke chain (`services/guardrail.py`), not inside the agent, so it
    covers a managed Harness and BYOC code alike. `anonymize` masks the entities and
    carries on; `block` refuses the turn with `guardrail.blocked`.
    """

    enabled: bool = False
    mode: Literal["anonymize", "block"] = "anonymize"


class MemoryConfig(BaseModel):
    short_term: bool = True
    long_term: bool = False
    # Per-agent AgentCore Memory selection. None ⇒ the workspace's shared
    # bootstrap memory (every spec written before this field existed reads back
    # that way). Ids follow the AgentCore `{name}-{suffix}` shape.
    memory_id: str | None = Field(
        default=None, max_length=128, pattern=r"^[a-zA-Z][a-zA-Z0-9_-]*$"
    )


class A2ASkill(BaseModel):
    """One AgentCard skill advertised by an A2A-protocol agent.

    Becomes both the A2A server's served card content and the Registry
    record's card `skills` entry — the routing surface other agents match on.
    """

    id: str = Field(pattern=r"^[a-z][a-z0-9_-]{0,63}$")
    name: str = Field(min_length=1, max_length=100)
    description: str = Field(default="", max_length=1000)
    tags: list[str] = Field(default_factory=list, max_length=10)


# AgentCore filesystemConfigurations mount-path contract: exactly one level under
# /mnt, 6-200 chars (see task research: runtime-filesystem-configurations).
MOUNT_PATH_RE = r"^/mnt/[a-zA-Z0-9._-]+/?$"

_S3_FILES_AP_RE = re.compile(
    r"^arn:aws[\w-]*:s3files:[^:]+:\d{12}:file-system/[^/]+/access-point/.+$"
)
_EFS_AP_RE = re.compile(
    r"^arn:aws[\w-]*:elasticfilesystem:[^:]+:\d{12}:access-point/.+$"
)


class SessionStorageFs(BaseModel):
    """Managed session storage (Preview) — per-session, reset on version update."""

    mount_path: str = Field(
        default="/mnt/workspace", pattern=MOUNT_PATH_RE, min_length=6, max_length=200
    )


class ByoMount(BaseModel):
    """Bring-your-own mount: an S3 Files or EFS access point."""

    access_point_arn: str = Field(min_length=20, max_length=2048)
    mount_path: str = Field(pattern=MOUNT_PATH_RE, min_length=6, max_length=200)


class VpcNetwork(BaseModel):
    """networkModeConfig for networkMode=VPC — required by BYO file systems."""

    subnets: list[str] = Field(min_length=1, max_length=8)
    security_groups: list[str] = Field(min_length=1, max_length=5)


class FilesystemConfig(BaseModel):
    """AgentCore Runtime filesystemConfigurations (≤1 session, ≤2 s3, ≤2 efs).

    session_storage defaults ON; an explicit JSON null disables it.
    """

    session_storage: SessionStorageFs | None = Field(default_factory=SessionStorageFs)
    s3_files: list[ByoMount] = Field(default_factory=list, max_length=2)
    efs: list[ByoMount] = Field(default_factory=list, max_length=2)

    @property
    def byo(self) -> bool:
        return bool(self.s3_files or self.efs)

    @model_validator(mode="after")
    def _check(self) -> "FilesystemConfig":
        paths = [m.mount_path.rstrip("/") for m in (*self.s3_files, *self.efs)]
        if self.session_storage:
            paths.append(self.session_storage.mount_path.rstrip("/"))
        if len(paths) != len(set(paths)):
            raise ValueError("filesystem mount paths must be unique")
        for mount in self.s3_files:
            if not _S3_FILES_AP_RE.match(mount.access_point_arn):
                raise ValueError(
                    f"'{mount.access_point_arn}' is not an S3 Files access point ARN"
                )
        for mount in self.efs:
            if not _EFS_AP_RE.match(mount.access_point_arn):
                raise ValueError(
                    f"'{mount.access_point_arn}' is not an EFS access point ARN"
                )
        return self


# HarnessAllowedTool from the bedrock-agentcore-control service model (2023-06-05):
# pattern ``\*|@?[^/]+(/[^/]+)?``, length 1–64.
_ALLOWED_TOOL_RE = re.compile(r"^(\*|@?[^/]+(/[^/]+)?)$")
_GATEWAY_TOOL_RE = re.compile(r"^[A-Za-z0-9_.-]{1,128}$")
MAX_GATEWAY_TOOLS = 250
ALLOWED_TOOL_MAX_LEN = 64

# ── BYOC (bring your own code) ──────────────────────────────────────────────

# What the uploaded/BYO artifact is. code_zip → direct-code Runtime
# (codeConfiguration); container_source → CodeBuild → ECR → Runtime;
# container_image → an existing private-ECR image, no build.
ByocArtifactKind = Literal["code_zip", "container_source", "container_image"]

# AgentManagedRuntimeType members the console offers (the service model also
# carries PYTHON_3_14/NODE_22; Python-only here because requirements resolution
# targets CPython wheels).
ByocPythonVersion = Literal["PYTHON_3_10", "PYTHON_3_11", "PYTHON_3_12", "PYTHON_3_13"]

# Ceiling for ``ByocConfig.allowed_models`` — each entry becomes one or two ARNs
# in the execution role's bedrock:InvokeModel statement, so the bound is an IAM
# policy-size sanity cap, not a model catalogue.
BYOC_ALLOWED_MODELS_MAX = 20
INFERENCE_PROFILE_PREFIXES = ("global.", "us.", "eu.", "apac.", "us-gov.")
_BYOC_MODEL_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9.:-]*$")
_BYOC_MODEL_ARN_RE = re.compile(
    r"^arn:aws(?:-cn|-us-gov)?:bedrock:[a-z0-9-]+:(?P<account>\d{12})?:"
    r"(?P<kind>foundation-model|inference-profile)/(?P<id>[A-Za-z0-9][A-Za-z0-9.:-]*)$"
)


def byoc_model_target(model_id: str) -> tuple[str, str]:
    """Validate a literal BYOC model selection and return (resource type, id).

    Custom identifiers remain usable without catalog lookup, but can never
    insert IAM wildcards. Profile targets must be derivable from a system
    inference-profile id; application profiles require a separate live lookup.
    """
    if model_id.startswith("arn:"):
        match = _BYOC_MODEL_ARN_RE.fullmatch(model_id)
        if match is None or (
            match["kind"] == "foundation-model" and match["account"] is not None
        ):
            raise ValueError(
                "BYOC models must be literal model IDs, foundation-model ARNs, "
                "or system inference-profile ARNs"
            )
        kind, target = match["kind"], match["id"]
    else:
        if _BYOC_MODEL_ID_RE.fullmatch(model_id) is None:
            raise ValueError("BYOC model IDs cannot contain wildcards, spaces, or IAM variables")
        target = model_id
        kind = (
            "inference-profile" if target.startswith(INFERENCE_PROFILE_PREFIXES)
            else "foundation-model"
        )
    if kind == "inference-profile":
        prefix = next((p for p in INFERENCE_PROFILE_PREFIXES if target.startswith(p)), "")
        if not prefix or len(target) == len(prefix):
            raise ValueError("BYOC inference profiles must use a global, us, eu, or apac model ID")
    return kind, target

# Private ECR in *some* account/region — the workspace match (this account, this
# region) is a resource check, done against the WorkspaceContext at request time,
# not here. Public registries (public.ecr.aws, docker.io) never match.
_PRIVATE_ECR_IMAGE_RE = re.compile(
    r"^(\d{12})\.dkr\.ecr\.([a-z0-9-]+)\.amazonaws\.com/"
    r"[a-z0-9._/-]+(:[A-Za-z0-9._-]+|@sha256:[0-9a-f]{64})$"
)


def parse_ecr_image_uri(uri: str) -> tuple[str, str] | None:
    """(account_id, region) of a private-ECR image URI, or None if not one."""
    match = _PRIVATE_ECR_IMAGE_RE.match(uri)
    return (match.group(1), match.group(2)) if match else None


class ByocProvenance(BaseModel):
    """Who uploaded what — stamped by the SERVER from the stored upload manifest
    (or, for container_image, from the describe_images check), never taken from
    the client. Rendered on the agent detail page."""

    sha256: str = ""
    size_bytes: int = 0
    original_filename: str = Field(default="", max_length=255)
    uploaded_by: str = Field(default="", max_length=128)
    uploaded_at: str = Field(default="", max_length=64)


class ByocConfig(BaseModel):
    """User-code deployment settings for method="byoc"."""

    artifact_kind: ByocArtifactKind
    # the staged zip (POST /api/agents/uploads) — code_zip / container_source
    upload_id: str | None = Field(default=None, max_length=64, pattern=r"^[A-Za-z0-9_-]+$")
    # an existing image — container_image only
    image_uri: str | None = Field(default=None, max_length=512)
    # code_zip only: must exist at the zip root (or the single top-level dir)
    entrypoint: str = Field(default="main.py", max_length=255)
    python_version: ByocPythonVersion = "PYTHON_3_13"
    # code_zip: resolve requirements.txt in the zip for linux/aarch64 at package
    # time (skipped when the zip has none). Never executes user code.
    install_requirements: bool = True
    # Documentation-only in v1: both values send {"prompt", "actor_id"}; "raw"
    # merely acknowledges the contract warning in the console. No payload mapper.
    invoke_contract: Literal["launchpad_prompt", "raw"] = "launchpad_prompt"
    # Every Bedrock model this agent's code may invoke (foundation-model or
    # inference-profile ids, or their supported ARNs). Custom ids are checked
    # for literal IAM-safe shape, without requiring a catalog match. The
    # execution role's bedrock:InvokeModel statement covers the
    # union; entry [0] is the PRIMARY model (= spec.model_id, injected as env
    # MODEL_ID). None ⇒ [spec.model_id] — every spec written before this field
    # existed reads back unchanged.
    allowed_models: list[str] | None = Field(default=None, min_length=1,
                                             max_length=BYOC_ALLOWED_MODELS_MAX)
    provenance: ByocProvenance | None = None

    @model_validator(mode="after")
    def _allowed_models_shape(self) -> "ByocConfig":
        if self.allowed_models is None:
            return self
        cleaned = [model_id.strip() for model_id in self.allowed_models]
        if any(not model_id for model_id in cleaned):
            raise ValueError("allowed_models entries cannot be empty")
        if len(cleaned) != len(set(cleaned)):
            raise ValueError("allowed_models entries must be unique")
        for model_id in cleaned:
            byoc_model_target(model_id)
        self.allowed_models = cleaned
        return self

    @model_validator(mode="after")
    def _artifact_inputs(self) -> "ByocConfig":
        if self.artifact_kind in ("code_zip", "container_source"):
            if not self.upload_id:
                raise ValueError(
                    f"byoc artifact_kind={self.artifact_kind} requires upload_id "
                    "(upload the zip via POST /api/agents/uploads first)"
                )
            if self.image_uri:
                raise ValueError("image_uri applies to artifact_kind=container_image only")
        else:  # container_image
            if not self.image_uri:
                raise ValueError("byoc artifact_kind=container_image requires image_uri")
            if self.upload_id:
                raise ValueError("upload_id applies to the zip artifact kinds only")
            if parse_ecr_image_uri(self.image_uri) is None:
                raise ValueError(
                    "image_uri must be a private ECR image in this account "
                    "(<account>.dkr.ecr.<region>.amazonaws.com/<repo>:<tag>); "
                    "public registries are refused"
                )
        if self.artifact_kind == "code_zip":
            entry = self.entrypoint
            if not entry.endswith(".py") or entry.startswith("/") or ".." in entry:
                raise ValueError("entrypoint must be a relative .py path inside the zip")
        return self


class AgentSpec(BaseModel):
    # The immutable slug — it names every AWS resource the agent owns.
    name: str = Field(pattern=r"^[a-z][a-z0-9-]{2,47}$")
    # Human-facing label (any Unicode, e.g. Chinese). Stored in the JSON spec only —
    # no ledger column and never sent to AWS — and, unlike ``name``, editable on
    # redeploy. Whitespace is trimmed; blank reads back as None (display falls
    # back to ``name``).
    display_name: str | None = Field(default=None, min_length=1, max_length=64)
    method: Method
    model_id: str = DEFAULT_MODEL_ID
    # Defaults to "bedrock" for BACKWARD COMPATIBILITY, not because it is the
    # preferred choice: agent specs are stored as JSON in the ledger and every
    # row written before this field existed is a Converse-API model. A "mantle"
    # default here would silently move all of them onto the Responses API on
    # their next re-publish. The Mantle default is a *form* default, applied by
    # the frontend wizard. Deliberately no cross-field validator against
    # model_id: custom ids are a first-class feature and the valid id space
    # cannot be enumerated from the account, so any check would be guesswork.
    # A wrong pairing surfaces as an AWS CREATE_FAILED + failureReason.
    model_source: ModelSource = "bedrock"
    # Per-model-call output ceiling (harness ``bedrockModelConfig.maxTokens``) and
    # reasoning effort (harness ``bedrockModelConfig.additionalParams``). Both are
    # harness-only and optional: every spec written before they existed reads back as
    # None and sends exactly the request it always did. Neither is a spend cap — the
    # harness loop is bounded separately by ``max_iterations`` / ``timeout_seconds``.
    max_tokens: int | None = Field(default=None, ge=1, le=MAX_TOKENS_CEILING)
    reasoning_effort: ReasoningEffort | None = None
    # Consumed by the container method only. The single-valued default is what
    # makes a future second SDK cheap: every container spec already on disk —
    # including those written before this field existed — reads back as the
    # Claude Agent SDK instead of being ambiguous.
    agent_sdk: AgentSdk = "claude_agent_sdk"
    # Non-empty for every method except byoc (enforced in _byoc_constraints):
    # BYOC code carries its own prompt — the platform has no template to put one in.
    system_prompt: str = Field(default="", max_length=20000)
    # Durable production defaults applied by experiment promotion. Config
    # bundles may override these per request while an A/B test is active.
    tool_description_overrides: dict[str, str] = Field(
        default_factory=dict, max_length=100
    )
    tools: list[ToolRef] = Field(default_factory=list)
    # Platform-owned local tool sets inlined into the generated agent (zip_runtime
    # only in v1). Rendered from this field at *generation* time — never
    # materialized into spec.code/code_bundle, because either of those flips
    # experiment_capability to "custom-source-unverified".
    toolkits: list[Toolkit] = Field(default_factory=list, max_length=2)
    skills: list[str] = Field(default_factory=list)
    # Native Harness capabilities are opt-in, independently of ToolConfig attachments.
    native_tools: list[Literal["shell", "file_operations"]] = Field(
        default_factory=list, max_length=2
    )
    # Harness ``allowedTools`` patterns (harness method only; the other methods ignore
    # it). None derives access from final attachments, Skills and native_tools.
    # An explicit list overrides derivation, including "*" and the empty list.
    # Pattern per the service model: ``*`` or ``@?[^/]+(/[^/]+)?``, ≤ 64 chars.
    allowed_tools: list[str] | None = Field(default=None, max_length=50)
    # extra pip requirements for zip_runtime/studio agents (on top of the template base set)
    requirements: list[str] = Field(default_factory=list)
    # pre-generated agent code (studio method) — bypasses the strands template
    code: str | None = Field(default=None, max_length=200000)
    # multi-file agent source (harness conversion) — relpath → content; must
    # contain main.py, which becomes the runtime entrypoint
    code_bundle: dict[str, str] | None = None
    # provenance of a harness→runtime conversion: {agent_id, agent_name, harness_arn}
    source_harness: dict[str, str] | None = None
    # per-capability wiring outcome of a conversion (memory/kb_gateway/…) — UI renders it
    conversion_notes: dict[str, str] | None = None
    # Strands Studio canvas graph {nodes, edges, graphMode} — persisted for later edit/re-publish
    studio_flow: dict[str, Any] | None = None
    memory: MemoryConfig = Field(default_factory=MemoryConfig)
    guardrail: GuardrailConfig = Field(default_factory=GuardrailConfig)
    env: dict[str, str] = Field(default_factory=dict)
    max_iterations: int = Field(default=100, ge=1, le=100)
    timeout_seconds: int = Field(default=600, ge=10, le=3600)
    # AgentCore Runtime persistent storage. Session storage mounts on the harness,
    # zip_runtime/studio and container methods; BYO mounts are container-only.
    filesystem: FilesystemConfig = Field(default_factory=FilesystemConfig)
    # VPC networkModeConfig; mandatory whenever a BYO file system is mounted
    network: VpcNetwork | None = None
    # Managed KBs mounted on this agent. Two channels, picked by method:
    #   harness           → launchpad-kb-gw attached as an agentcore_gateway tool
    #                       (per-KB Retrieve + per-agent AgenticRetrieveStream)
    #   zip_runtime /      → a kb_search tool baked into the generated code that
    #   container            calls bedrock-agent-runtime:Retrieve with the runtime
    #                        execution role (no gateway, single-shot retrieval)
    # See app/templates/kb_support.py and .trellis/spec/launchpad/managed-kb.md.
    knowledge_bases: list[KnowledgeBaseRef] = Field(default_factory=list, max_length=10)
    # Runtime service protocol. "a2a" deploys a standard A2A JSON-RPC server
    # (port 9000, serverProtocol=A2A) — zip_runtime only in v1.
    protocol: Literal["http", "a2a"] = "http"
    # AgentCard skills served by the A2A server and published to the Registry
    a2a_skills: list[A2ASkill] = Field(default_factory=list, max_length=20)
    # Bring-your-own-code settings — required iff method="byoc"
    byoc: ByocConfig | None = None
    # Inbound authentication of this agent's Runtime. None = inherit the
    # workspace default (resolved at deploy time by
    # ``schemas.inbound_auth.resolve_inbound_auth``); an explicit value pins the
    # agent regardless of later workspace-default changes. The RESOLVED choice
    # is snapshotted onto the Agent row (``inbound_auth_mode`` /
    # ``inbound_auth_config``) by the deploy stage, so consumers never re-derive.
    inbound_auth: InboundAuth | None = None

    @model_validator(mode="after")
    def _inbound_auth_supported(self) -> "AgentSpec":
        """An explicit JWT choice is refused where no Runtime authorizer exists.

        The managed harness is invoked via InvokeHarness (SigV4) and A2A
        runtimes are called by other agents over SigV4 JSON-RPC — deploying
        either with a JWT authorizer would produce an agent the platform cannot
        invoke. Inheritance is handled separately: ``resolve_inbound_auth``
        quietly resolves these methods to IAM under a JWT workspace default.
        """
        if self.inbound_auth is None or self.inbound_auth.mode != "jwt":
            return self
        if self.method not in JWT_CAPABLE_METHODS:
            raise ValueError(
                f"inbound_auth mode 'jwt' is not supported by the {self.method} "
                "method — only Runtime-backed agents (zip_runtime, studio, "
                "container, byoc) can carry a JWT authorizer"
            )
        if self.protocol == "a2a":
            raise ValueError(
                "inbound_auth mode 'jwt' is not supported by protocol=a2a "
                "runtimes — A2A peers invoke over SigV4"
            )
        return self

    @field_validator("display_name", mode="before")
    @classmethod
    def _trim_display_name(cls, v: Any) -> Any:
        if isinstance(v, str):
            v = v.strip()
            return v or None
        return v

    @model_validator(mode="after")
    def _byoc_constraints(self) -> "AgentSpec":
        """BYOC scope for v1 — and the non-byoc system_prompt floor.

        The platform does not generate BYOC code, so it cannot wire toolkits,
        skills, tools or knowledge bases into it — those are refused rather than
        silently ignored. ``system_prompt`` stays mandatory for every other
        method (it used to be ``min_length=1`` on the field; the floor moved here
        so BYOC — whose code owns its own prompt — can omit it).
        """
        if self.method != "byoc":
            if not self.system_prompt:
                raise ValueError("system_prompt must not be empty")
            if self.byoc is not None:
                raise ValueError("byoc settings apply to method='byoc' only")
            return self
        if self.byoc is None:
            raise ValueError("method='byoc' requires the byoc settings block")
        if self.protocol != "http":
            raise ValueError("byoc agents speak the HTTP runtime contract only in v1")
        for field_name in ("toolkits", "skills", "knowledge_bases"):
            if getattr(self, field_name):
                raise ValueError(
                    f"{field_name} are not supported by the byoc method in v1 — "
                    "the platform does not generate this agent's code, so it "
                    "cannot wire them in; configure them inside your own code"
                )
        # byoc tools are outbound-auth declarations only: an entry carrying
        # ``auth`` drives IAM grants + LAUNCHPAD_OUTBOUND_AUTH, and the member's
        # own code performs the exchange. A tool without auth would ask the
        # platform to wire code it does not generate — refused.
        for tool in self.tools:
            if tool.auth is None:
                raise ValueError(
                    "tools are not supported by the byoc method in v1 unless they "
                    "carry an auth block — byoc tools are outbound-auth declarations "
                    "for your own code; wire the tool itself inside your code"
                )
        if self.code or self.code_bundle:
            raise ValueError(
                "byoc deploys the uploaded artifact — code/code_bundle are not used"
            )
        if self.requirements:
            raise ValueError(
                "byoc resolves requirements.txt from inside the uploaded zip — "
                "spec.requirements is not used"
            )
        models = self.byoc.allowed_models
        if models is not None:
            # model_id is the PRIMARY model and must equal allowed_models[0]:
            # a client that sends only the list gets the first entry as primary;
            # a client that sends both gets its model_id moved to the front so
            # the two fields can never disagree about which model is primary.
            if "model_id" not in self.model_fields_set:
                self.model_id = models[0]
            elif self.model_id not in models:
                raise ValueError(
                    f"model_id {self.model_id!r} must be one of byoc.allowed_models "
                    "— it is the primary model (env MODEL_ID)"
                )
            elif models[0] != self.model_id:
                models.remove(self.model_id)
                models.insert(0, self.model_id)
        # Omitting the list still authorizes model_id, so it needs the same
        # literal-resource validation as explicit allowlist entries.
        byoc_model_target(self.model_id)
        return self

    @property
    def allowed_model_ids(self) -> list[str]:
        """Every model this agent's execution role may invoke; entry [0] is the
        primary (= ``model_id``). Only byoc can carry more than one — every other
        method (and every byoc spec without the list) reads back as [model_id]."""
        if self.byoc and self.byoc.allowed_models:
            return list(self.byoc.allowed_models)
        return [self.model_id]

    @model_validator(mode="after")
    def _tool_auth_placement(self) -> "AgentSpec":
        """Where an ``auth`` block may sit, and what a ``rest`` tool must carry.

        ``rest`` tools and ``auth`` blocks are honoured by zip_runtime (the strands
        template renders the identity client) and byoc (declaration only), so every
        other method refuses them instead of deploying an agent whose console
        shows auth its runtime never performs. Harness/container/studio agents get
        outbound auth through a Gateway target bound to a Connection instead.
        """
        carriers = [t for t in self.tools if t.auth is not None or t.type == "rest"]
        if not carriers:
            return self
        if self.method not in TOOL_AUTH_METHODS:
            raise ValueError(
                "rest tools / tool auth are supported by the zip_runtime and byoc "
                "methods only — attach a Gateway target bound to a Connection for "
                "the other methods"
            )
        if self.protocol != "http":
            raise ValueError(
                "rest tools / tool auth are not supported by protocol=a2a runtimes"
            )
        if self.code or self.code_bundle:
            raise ValueError(
                "rest tools / tool auth cannot be combined with code/code_bundle — "
                "those specs deploy their own source and never render the identity "
                "client"
            )
        names = [t.name for t in carriers]
        if len(names) != len(set(names)):
            raise ValueError("rest / auth tool names must be unique")
        for tool in self.tools:
            if tool.type == "rest" and not _REST_TOOL_NAME_RE.match(tool.name):
                raise ValueError(
                    f"rest tool name {tool.name!r} must match {_REST_TOOL_NAME_RE.pattern} "
                    "(it becomes the model-facing function name)"
                )
            if tool.type == "rest" and self.method != "byoc":
                url = str((tool.config or {}).get("url") or "")
                if not url.startswith(("http://", "https://")):
                    raise ValueError(
                        f"rest tool '{tool.name}' requires config.url (http/https)"
                    )
            if tool.auth is not None and tool.type not in ("rest", "mcp"):
                raise ValueError(
                    f"tool '{tool.name}': auth applies to rest and mcp tools only — "
                    "gateway tools are authenticated by the gateway's own targets"
                )
        return self

    @model_validator(mode="after")
    def _a2a_constraints(self) -> "AgentSpec":
        if self.protocol == "a2a" and self.method != "zip_runtime":
            raise ValueError(
                "the A2A protocol is only supported by the zip_runtime method in v1"
            )
        if self.protocol == "a2a" and (self.code or self.code_bundle):
            raise ValueError(
                "protocol=a2a always uses the platform A2A template — "
                "custom code/code_bundle is not supported in v1"
            )
        if self.a2a_skills and self.protocol != "a2a":
            raise ValueError("a2a_skills require protocol=a2a")
        if self.protocol == "a2a":
            ids = [s.id for s in self.a2a_skills]
            if len(ids) != len(set(ids)):
                raise ValueError("a2a_skills ids must be unique")
        return self

    @model_validator(mode="after")
    def _inference_knobs_supported(self) -> "AgentSpec":
        """Refuse a knob the target cannot honour instead of dropping it silently.

        ``max_tokens`` maps only onto the managed harness request. ``reasoning_effort``
        is an OpenAI-specific request field: sent to a Claude, Nova or other model it
        is either rejected by the provider or ignored, so it is accepted only for an
        OpenAI model on native Bedrock (Converse), the one pass-through shape the
        platform has verified. Bedrock Mantle (Responses API) is refused rather than
        guessed at.
        """
        if self.max_tokens is not None and self.method != "harness":
            raise ValueError("max_tokens is supported by the harness method only")
        if self.reasoning_effort is None:
            return self
        if self.method != "harness":
            raise ValueError("reasoning_effort is supported by the harness method only")
        if not is_openai_model_id(self.model_id):
            raise ValueError(
                f"reasoning_effort applies to OpenAI GPT-5.x / GPT-6 models only; "
                f"{self.model_id!r} is not an OpenAI model id"
            )
        if self.model_source != "bedrock":
            raise ValueError(
                "reasoning_effort is supported for OpenAI models on native Bedrock "
                "(model_source=bedrock, Converse) only — the Bedrock Mantle Responses "
                "pass-through shape is not verified, so it is refused rather than guessed"
            )
        return self

    @model_validator(mode="after")
    def _native_tools_supported(self) -> "AgentSpec":
        if self.native_tools and self.method != "harness":
            raise ValueError("native_tools is supported by the harness method only")
        if len(self.native_tools) != len(set(self.native_tools)):
            raise ValueError("native_tools must be unique")
        return self

    @model_validator(mode="after")
    def _allowed_tools_shape(self) -> "AgentSpec":
        for pattern in self.allowed_tools or []:
            if not 1 <= len(pattern) <= ALLOWED_TOOL_MAX_LEN:
                raise ValueError(
                    f"allowed_tools entry {pattern!r} must be 1–{ALLOWED_TOOL_MAX_LEN} characters"
                )
            if not _ALLOWED_TOOL_RE.match(pattern):
                raise ValueError(
                    f"allowed_tools entry {pattern!r} must match '*' or '@?name(/tool)?'"
                )
        return self

    @model_validator(mode="after")
    def _requirements_are_pinned(self) -> "AgentSpec":
        # Refused here rather than mid-deploy so the console shows the problem
        # before a build starts. Only the caller-supplied list is checked; the
        # platform's own lists keep their ranges by design and the package
        # stage's hashed lockfile is what makes the resolved set reproducible.
        assert_all_pinned(self.requirements)
        return self

    @model_validator(mode="after")
    def _byo_needs_vpc(self) -> "AgentSpec":
        # Only the container method wires VPC networking; the harness and Strands
        # zip runtimes mount managed session storage alone. Refused, not dropped,
        # so a spec never shows a mount its runtime does not have.
        if self.filesystem.byo and self.method != "container":
            raise ValueError(
                "BYO file systems (S3 Files / EFS) are supported by the container "
                "method only; harness and Strands agents mount session storage"
            )
        if self.filesystem.byo and self.network is None:
            raise ValueError(
                "BYO file systems (S3 Files / EFS) require VPC network configuration"
            )
        return self

    @model_validator(mode="after")
    def _kb_method_supported(self) -> "AgentSpec":
        if self.knowledge_bases and self.method not in KB_METHODS:
            raise ValueError(
                "knowledge_bases are supported by the harness, zip_runtime and "
                "container methods; the Strands Studio canvas (studio) has no "
                "retrieval tool contract yet"
            )
        if self.knowledge_bases and self.protocol == "a2a":
            raise ValueError(
                "knowledge_bases are not supported by protocol=a2a runtimes "
                "(the A2A template carries no retrieval tool)"
            )
        return self

    @model_validator(mode="after")
    def _toolkits_supported(self) -> "AgentSpec":
        """Toolkits only exist where the Strands template actually renders.

        Rejected rather than silently dropped: a toolkit that quietly vanished
        would leave an agent whose console shows five tools and whose runtime has
        none, and whose readiness panel then waits forever for calls that can
        never happen.
        """
        if not self.toolkits:
            return self
        if self.method != "zip_runtime":
            raise ValueError(
                "toolkits are supported by the zip_runtime method only — the managed "
                "harness has no generated code to inline them into, and the Strands "
                "Studio canvas and Claude Agent SDK container generate their own"
            )
        if self.protocol != "http":
            raise ValueError(
                "toolkits are not supported by protocol=a2a runtimes "
                "(the A2A server uses its own template)"
            )
        if self.code or self.code_bundle:
            raise ValueError(
                "toolkits cannot be combined with code/code_bundle — those specs "
                "deploy their own source and never render the Strands template"
            )
        if len(self.toolkits) != len(set(self.toolkits)):
            raise ValueError("toolkits must be unique (a toolkit inlined twice "
                             "would redefine its functions)")
        return self

    @model_validator(mode="after")
    def _code_bundle_valid(self) -> "AgentSpec":
        if self.code_bundle is None:
            return self
        if self.code:
            raise ValueError("code and code_bundle are mutually exclusive")
        if "main.py" not in self.code_bundle:
            raise ValueError("code_bundle must contain main.py (the entrypoint)")
        if len(self.code_bundle) > 64:
            raise ValueError("code_bundle exceeds 64 files")
        total = 0
        for path, content in self.code_bundle.items():
            pure = PurePosixPath(path)
            if pure.is_absolute() or ".." in pure.parts or "\\" in path:
                raise ValueError(f"code_bundle path '{path}' is not a safe relative path")
            total += len(content.encode("utf-8"))
        if total > 1_000_000:
            raise ValueError("code_bundle exceeds 1MB of source")
        return self

    @model_validator(mode="after")
    def _tool_description_overrides_valid(self) -> "AgentSpec":
        for name, description in self.tool_description_overrides.items():
            if not name or len(name) > 200:
                raise ValueError("tool description override names must be 1-200 characters")
            if len(description) > 4000:
                raise ValueError(
                    f"tool description override for '{name}' exceeds 4000 characters"
                )
        return self


class InvokeRequest(AttachmentRequest):
    session_id: str | None = SessionIdField
    actor_id: str = "default"


class InvokeResponse(BaseModel):
    text: str
    session_id: str
    latency_ms: int
    # T35: "rule" when a curated answer short-circuited the model, "model" otherwise.
    # Must be on the console response as well as `/v1` — one invoke chain, one contract —
    # or a curated answer reads as the model's own.
    answered_by: str = "model"


def _clean_resource_ids(ids: list[str], label: str) -> list[str]:
    cleaned = list(dict.fromkeys(resource_id.strip() for resource_id in ids))
    if any(not resource_id for resource_id in cleaned):
        raise ValueError(f"{label} IDs cannot be empty")
    if len(cleaned) > 100:
        raise ValueError(f"cannot import more than 100 unique {label} IDs")
    if any(len(resource_id) > 256 for resource_id in cleaned):
        raise ValueError(f"{label} IDs cannot exceed 256 characters")
    return cleaned


class RuntimeImportRequest(BaseModel):
    """One import call carries both discovered resource kinds; either may be empty."""

    runtime_ids: list[str] = []
    harness_ids: list[str] = []

    @model_validator(mode="after")
    def _unique_bounded_ids(self) -> "RuntimeImportRequest":
        self.runtime_ids = _clean_resource_ids(self.runtime_ids, "Runtime")
        self.harness_ids = _clean_resource_ids(self.harness_ids, "Harness")
        if not self.runtime_ids and not self.harness_ids:
            raise ValueError("provide at least one Runtime ID or Harness ID to import")
        return self
